package updater

import (
	"bytes"
	"strings"
	"testing"
)

func TestRenderedHTMLContainsAsyncUpdateHooks(t *testing.T) {
	var output bytes.Buffer
	data := PageData{
		Theme: "dark",
	}
	if err := pageTemplate.Execute(&output, data); err != nil {
		t.Fatal(err)
	}
	rendered := output.String()
	surface := rendered + "\n" + uiJS + "\n" + uiCSS
	for _, expected := range []string{
		`class="dashboard-hero"`,
		`rel="icon" href="/favicon.ico?v=`,
		`rel="shortcut icon" href="/favicon.ico?v=`,
		`rel="stylesheet" href="/assets/ui.css?v=`,
		`src="/assets/ui.js?v=`,
		`defer`,
		`id="dashboard-summary"`,
		`id="store-status-modal"`,
		`role="dialog"`,
		`aria-modal="true"`,
		`id="store-status-close"`,
		`data-store-status-open`,
		`data-store-status-close`,
		`openStoreStatusModal`,
		`closeStoreStatusModal`,
		`id="store-scan-health-summary"`,
		`id="store-scan-health-body"`,
		`id="store-rescan-button"`,
		`id="store-diagnostics-export-button"`,
		`id="package-diagnostics-modal"`,
		`id="package-diagnostics-body"`,
		`data-package-diagnostics-open`,
		`data-package-diagnostics-close`,
		`openPackageDiagnosticsModal`,
		`closePackageDiagnosticsModal`,
		`packageDiagnosticsButton`,
		`diagnostics-button`,
		`/api/store/diagnostics/export`,
		`id="summary-updates"`,
		`id="summary-packages"`,
		`id="summary-managers"`,
		`id="summary-automation"`,
		`id="toast-region"`,
		`id="shutdown-form"`,
		`id="shutdown-button"`,
		`id="updates-section"`,
		`id="install-progress"`,
		`id="install-progress-status"`,
		`id="update-progress"`,
		`id="update-progress-status"`,
		`role="status"`,
		`aria-live="polite"`,
		`aria-busy="false"`,
		`role="progressbar"`,
		`aria-valuetext="In progress"`,
		`function progressBar(label)`,
		`id="updates-prev"`,
		`id="updates-page-status"`,
		`id="updates-next"`,
		`class="update-all-form"`,
		`id="search-form"`,
		`<span class="sr-only">Search and install packages</span>`,
		`id="search-prev"`,
		`id="search-page-status"`,
		`id="search-next"`,
		`id="search-provenance"`,
		`Manager / Backend`,
		`Exact ID`,
		`sourceLabel`,
		`executionBackendLabel`,
		`installRouteText`,
		`renderSearchProvenance`,
		`searchCommandResult`,
		`data.command_results`,
		`searchFailureReason`,
		`searchShownPhrase`,
		`searchOriginLabel`,
		`searchManagerLabel`,
		` unavailable;`,
		` search failed;`,
		`searchMatchCell`,
		`searchManagerBackendCell`,
		`searchActionCell`,
		`pkg.match_reason`,
		`package-id`,
		`install-route`,
		`action="/api/install"`,
		`aria-label="Install `,
		`action="/api/managers/install"`,
		`enqueueUpdateRequest`,
		`rowUpdateState`,
		`activeUpdateJobRunning`,
		`Queued`,
		`postCommandPayload`,
		`postForm("/api/status/refresh"`,
		`X-Windows-Updater-WebUI`,
		`form.id === "shutdown-form"`,
		`postForm("/shutdown"`,
		`payload.result && !payload.result.ok`,
		`Application scan completed with errors`,
		`Could not update startup setting`,
		`Could not update auto-update settings`,
		`allow_unknown_version`,
		`allow_pinned`,
		`id="update-allow-unknown"`,
		`id="update-allow-pinned"`,
		`Global update options`,
		`<th>Select</th>`,
		`aria-label="Select `,
		`aria-label="Auto-update for `,
		`aria-pressed="`,
		`data-package-name`,
		`appendGlobalUpdateOptions`,
		`allowUnknownVersionUpdates`,
		`allowPinnedUpdates`,
		`packageBulkUpdateable`,
		`storeAssessmentActive`,
		`storeUpdateState`,
		`if(pkg && pkg.manager === "store"){`,
		`return "unknown";`,
		`storeScanHealth`,
		`renderStoreScanHealth`,
		`Provider diagnostics`,
		`Exact target unavailable`,
		`Rescan required`,
		`accepted_not_verified`,
		`Verifying update`,
		`Store update status is unknown. Review scan health.`,
		`state-badge`,
		`updatePageSize = 10`,
		`showToast`,
		`Math.max(duration || 10000, 10000)`,
		`pauseToastTimers`,
		`resumeToastTimers`,
		`document.hidden`,
		`visibilitychange`,
		`toast-close`,
		`toast-region`,
		`toast-progress`,
		`--toast-progress`,
		`requestAnimationFrame`,
		`new EventSource`,
		`api("/api/events"`,
		`AbortController`,
		`statusRequestSeq`,
		`packageRequestSeq`,
		`scheduleStatusLoad`,
		`schedulePackageLoad`,
		`bottom:18px`,
		`startUpdateJob`,
		`checkActiveUpdateJob`,
		`api("/api/jobs/status"`,
		`api("/api/jobs")`,
		`postForm("/api/inventory/refresh"`,
		`postForm(cancelID ? "/api/jobs/cancel"`,
		`id="cancel-updates-button"`,
		`id="update-preflight-panel"`,
		`id="confirm-update-job"`,
		`id="cancel-update-preflight"`,
		`id="update-preflight-summary"`,
		`id="update-preflight-body"`,
		`id="update-preflight-excluded"`,
		`buildUpdatePreflight`,
		`renderUpdatePreflight`,
		`confirmPendingUpdateJob`,
		`hideUpdatePreflight`,
		`packageRiskNotes`,
		`pinned-package override`,
		`id="update-results-panel"`,
		`id="retry-failed-updates"`,
		`id="update-results-summary"`,
		`id="update-results-body"`,
		`renderUpdateResultPanel`,
		`renderLatestUpdateResult`,
		`retryFailedUpdateResults`,
		`Succeeded`,
		`Failed`,
		`Skipped`,
		`Cancelled`,
		`status.package_keys`,
		`applyUpdateJobPackageKeys`,
		`response.status === 409 && status.running`,
		`active && !status.cancel_requested`,
		`installFromForm`,
		`waitForJob`,
		`jobComplete`,
		`jobSucceeded`,
		`reconcileJobs`,
		`activeServerJobs`,
		`upsertServerJob`,
		`renderSearchTable`,
		`searchPageSize = 10`,
		`installManagerFromForm`,
		`refreshStatusAfterManagerInstall`,
		`setInstallProgress`,
		`install-progress-panel`,
		`refreshPackagesAfterUpdate`,
		`id="session-log-panel"`,
		`class="log-tab active"`,
		`role="tablist"`,
		`aria-orientation="horizontal"`,
		`role="tab"`,
		`aria-controls="session-log"`,
		`tabindex="0"`,
		`tabindex="-1"`,
		`role="tabpanel"`,
		`aria-labelledby="log-tab-all"`,
		`data-log-category="all"`,
		`data-log-category="application"`,
		`data-log-category="searches"`,
		`data-log-category="updates"`,
		`data-log-category="winget"`,
		`data-log-category="store"`,
		`data-log-category="chocolatey"`,
		`id="log-search"`,
		`id="log-connection-status"`,
		`class="hero-topline"`,
		`connection-badge`,
		`Log reconnecting`,
		`setLogConnectionState`,
		`maxBrowserLogEntries`,
		`maxBrowserLogBytes`,
		`trimBrowserLogs`,
		`prepareLogEntry`,
		`_formatted`,
		`logBytes`,
		`id="copy-log-view"`,
		`id="export-log-view"`,
		`id="clear-log-view"`,
		`id="log-autoscroll"`,
		`activeLogCategory`,
		`logSearchQuery`,
		`filteredLogLines`,
		`setActiveLogCategory`,
		`focusAdjacentLogTab`,
		`ArrowRight`,
		`ArrowLeft`,
		`Home`,
		`End`,
		`clearCurrentLogView`,
		`exportLogs`,
		`copyLogView`,
		`navigator.clipboard.writeText`,
		`document.execCommand("copy")`,
		`api("/api/logs"`,
		`api("/api/logs/export"`,
		`id="updates-body"`,
		`id="installed-search"`,
		`for="installed-search">Filter installed packages`,
		`for="log-search">Search active log`,
		`id="installed-page-status"`,
		`packageMatchesInstalledSearch`,
		`packageAvailableCell`,
		`packageAvailableCell(pkg, {diagnostics:true})`,
		`packageAvailableCell(pkg, {statusBadge:false, compact:true})`,
		`available-cell`,
		`managersRendered`,
		`renderUpdatesTable`,
		`renderInstalledTable`,
		`installedAction`,
		`updating-current`,
		`managerAvailabilityText`,
		`managerDisplayDetails`,
		`renderDashboardSummary`,
		`managerLabel`,
		`backendLabel`,
		`function icon(name)`,
		`function spinner()`,
		`function loadingText(message)`,
		`function setLoadingContent(target, message, loading)`,
		`function loadingTableRow(colspan, message)`,
		`class="spinner"`,
		`class="loading-message"`,
		`class="loading-text"`,
		`conic-gradient`,
		`will-change:transform`,
		`--spinner-angle`,
		`function startSpinnerLoop()`,
		`function updateSpinnerPhase()`,
		`function observeSpinnerPresence()`,
		`MutationObserver`,
		`requestAnimationFrame(tick)`,
		`prefers-reduced-motion:reduce`,
		`class="button-icon"`,
		`class="summary-card`,
		`compactNoticeText`,
		`truncateNoticeText`,
		`firstMeaningfulOutputLine`,
		`See Session Log for full output.`,
		`max-height:96px`,
		`manager.inventory_available`,
		`pkg.action_backend`,
		`Inventory only`,
		`Store apps detected via`,
		`store-cli-resolved`,
	} {
		if !strings.Contains(surface, expected) {
			t.Fatalf("rendered page or embedded assets did not contain %q", expected)
		}
	}
	for _, unexpected := range []string{
		`Inventory: `,
		`Actions: `,
		`unknown-confirm`,
		`pinned-confirm`,
		`Update Anyway`,
		`Available Usage: store`,
		`Usage: store <command>`,
		`store-health-compact`,
		`? "Current" : "-"`,
		`action="/install"`,
		`action="/manager/install"`,
		`action="/update"`,
		`action="/update-all"`,
		`class="status-grid"`,
		`{{if .CommandResult}}`,
		`{{if .ActionResults}}`,
		`{{if .Scan}}`,
		`showNotice("Refreshing package status...", true)`,
		`showNotice(rowUpdateProgressMessage(), true)`,
		`rowUpdateQueue`,
		`rowUpdateActive`,
		`processRowUpdateQueue`,
		`rowUpdateQueueActive`,
		`queuedRowUpdateKeys`,
		`showNotice(message, active || !!(status && status.refresh_started))`,
		`showNotice(message || "Starting updates...", true)`,
		`data-token`,
		`name="token"`,
		`searchParams.set("token"`,
		`PFN:`,
		`packageNameCell(pkg, {diagnostics:true})`,
		`Session log disconnected. Reconnecting`,
		`Log disconnected; retrying`,
	} {
		if strings.Contains(surface, unexpected) {
			t.Fatalf("rendered page or embedded assets should not contain %q", unexpected)
		}
	}
	for _, unexpectedInline := range []string{`<style>`, `<script>!function`, `<script>`} {
		if strings.Contains(rendered, unexpectedInline) {
			t.Fatalf("rendered page should not contain inline asset block %q", unexpectedInline)
		}
	}
	progressIndex := strings.Index(rendered, `id="update-progress"`)
	updatesIndex := strings.Index(rendered, `Updates Available`)
	if progressIndex < 0 || updatesIndex < 0 || progressIndex > updatesIndex {
		t.Fatalf("expected update progress banner before updates table, progress=%d updates=%d", progressIndex, updatesIndex)
	}
	installProgressIndex := strings.Index(rendered, `id="install-progress"`)
	searchResultsIndex := strings.Index(rendered, `id="search-results-panel"`)
	if installProgressIndex < 0 || searchResultsIndex < 0 || installProgressIndex > searchResultsIndex {
		t.Fatalf("expected install progress banner before search results, progress=%d search=%d", installProgressIndex, searchResultsIndex)
	}
}
